### ISSUE TITLE
Describe related work

### ISSUE THREAD

**Issue by dionyziz** [mutantzombie/SessionOriginSecurity#1]
The document is missing references to related work such as the [first-party cookies RFC](https://tools.ietf.org/html/draft-west-first-party-cookies-00) by M. West. We should add references to those drafts and explain why or how we are different.

**Comment by mutantzombie** [comment]
If there's related work from another Mike, then that's possibly sufficient criteria. ;)

Though this hasn't been revisited since 2013, it's not a bad idea to maintain with references to ongoing work that tries to address CSRF.

**Comment by dionyziz** [comment]
[Mike West](https://twitter.com/mikewest) is [pursuing](https://twitter.com/mikewest/status/709676633712676864) implementing first-party cookies [in Chrome 51](https://codereview.chromium.org/1783813002), so this should address the issue [after April 8th](https://www.chromium.org/developers/calendar). We're planning to also [talk about first-party](https://www.blackhat.com/asia-16/briefings.html#dionysios-zindros) cookies in Black Hat Asia on March 31st, so there should be some buzz around it over the next month.

I love the idea behind SOS cookies. However, I think since there is some push from Google, we're going to be using the name "first-party cookies" instead. To be fair, I think SOS cookies deserve a reference in the RFC, since you talked about these very similar ideas first – we should talk to Mike to make an acknowledgment too.

**Comment by mutantzombie** [comment]
Thanks for taking the time to comment and call out this effort!
